// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Organisation struct {
	ID          uuid.UUID
	Name        string
	Description pgtype.Text
}

type User struct {
	ID        uuid.UUID
	Email     string
	FirstName string
	LastName  string
	Password  string
	Phone     pgtype.Text
}

type UserOrganisation struct {
	UserID uuid.UUID
	OrgID  uuid.UUID
}
