// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// pretty complicated query but should work
	// gets a user if it belongs to one of another user's
	// organisation
	FindUserInOrgs(ctx context.Context, arg FindUserInOrgsParams) (User, error)
	OrgAllWhereUser(ctx context.Context, userID uuid.UUID) ([]Organisation, error)
	OrgInsert(ctx context.Context, arg OrgInsertParams) (Organisation, error)
	OrgWhereUser(ctx context.Context, arg OrgWhereUserParams) (Organisation, error)
	OrganisationWhereId(ctx context.Context, id uuid.UUID) (Organisation, error)
	UserAddOrg(ctx context.Context, arg UserAddOrgParams) error
	UserInsert(ctx context.Context, arg UserInsertParams) (User, error)
	UserWhereEmail(ctx context.Context, email string) (User, error)
	UserWhereId(ctx context.Context, id uuid.UUID) (User, error)
}

var _ Querier = (*Queries)(nil)
